name: Pre-Release

on:
  push:
    tags:
      - "v*.*.*_pre-release"

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.7'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt install libmariadbclient-dev libmariadb3 libmariadb-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build poetry

      - name: Setup poetry for publish
        run: |
          poetry build
          poetry config repositories.test-pypi https://test.pypi.org/legacy/

      - name: Publish to testpypi.org
        run: |
          poetry publish -r test-pypi --no-interaction --username __token__ --password ${{ secrets.TEST_PYPI_TOKEN }}
