name: Release

on:
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.7'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build poetry

      - name: Setup poetry for publish
        run: |
          poetry build
          poetry config repositories.pypi https://pypi.org/legacy/

      - name: Publish to pypi.org
        run: |
          poetry publish -r pypi --no-interaction --username __token__ --password ${{ secrets.PYPI_TOKEN }}
